[package]
name = "contracts"
version = "0.1.0"
edition = "2023_10"

[dependencies]
pragma_lib = { git = "https://github.com/astraly-labs/pragma-lib" }
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.8.0" }
starknet = ">=2.4.0"

[[target.starknet-contract]]
